import type { Lesson } from "./data";
export const moreLessons: Lesson[] = [
  {
    id: 8,
    title: "The people in your life",
    subtitle: "Family, friends & familiar faces",
    icon: "heart",
    tip: "Meet the people in your everyday conversations.",
    phrases: [
      {
        ar: "أمي",
        latin: "immi",
        en: "My mother",
        tip: "The ending -i means “my.” Immi is a familiar way to refer to your mother.",
      },
      {
        ar: "أبوي",
        latin: "abooy",
        en: "My father",
        tip: "Abooy means “my father.” You may also hear the affectionate address “baba.”",
      },
      {
        ar: "أخوي",
        latin: "akhooy",
        en: "My brother",
        tip: "The kh in akhooy is one throaty sound, like the end of “loch.” The word already includes “my.”",
      },
      {
        ar: "أختي",
        latin: "ukhti",
        en: "My sister",
        tip: "Ukht means sister. Add -i to make ukhti: my sister.",
      },
      {
        ar: "صاحبي",
        latin: "saahbi",
        en: "My friend",
        note: "For a female friend: saahbti (صاحبتي).",
        tip: "Saahbi refers to a male friend. Use saahbti for a female friend, regardless of your own gender.",
      },
    ],
  },
  {
    id: 9,
    title: "Count me in",
    subtitle: "Your first five numbers",
    icon: "spark",
    tip: "Practice counting slowly before speeding up.",
    phrases: [
      {
        ar: "واحد",
        latin: "waahad",
        en: "One",
        tip: "Waahad is the counting form of one. When describing a feminine noun, you’ll hear waahdeh.",
      },
      {
        ar: "تنين",
        latin: "tnein",
        en: "Two",
        tip: "Tnein is a common spoken form of two. You may also hear it with a short sound at the beginning: itnein.",
      },
      {
        ar: "تلاتة",
        latin: "tlaateh",
        en: "Three",
        tip: "Notice the t sounds in tlaateh. This spoken form differs from the th sounds in formal Arabic thalaatha.",
      },
      {
        ar: "أربعة",
        latin: "arba‘a",
        en: "Four",
        tip: "The mark in arba‘a represents ع, a throat sound. Keep the two a sounds on either side of it distinct.",
      },
      {
        ar: "خمسة",
        latin: "khamseh",
        en: "Five",
        tip: "Count all five in order: waahad, tnein, tlaateh, arba‘a, khamseh. Then try counting backward.",
      },
    ],
  },
  {
    id: 10,
    title: "A little market chat",
    subtitle: "Prices, choices & something to take home",
    icon: "food",
    tip: "A short question can open a whole market conversation.",
    phrases: [
      {
        ar: "قديش؟",
        latin: "addeish?",
        en: "How much?",
        tip: "Use addeish to ask an amount or a price. This is a common urban pronunciation; the ق varies across communities.",
      },
      {
        ar: "قديش هادا؟",
        latin: "addeish haada?",
        en: "How much is this?",
        note: "For a feminine item: addeish haadi? (قديش هادي؟).",
        tip: "Point to an item and ask addeish haada? Haada is “this” for a masculine noun; haadi is the feminine form.",
      },
      {
        ar: "غالي",
        latin: "ghaali",
        en: "Expensive",
        note: "Feminine: ghaalyeh (غالية).",
        tip: "Gh represents غ, a voiced throaty sound. Ghaali describes a masculine item; ghaalyeh describes a feminine one.",
      },
      {
        ar: "رخيص",
        latin: "rkhees",
        en: "Inexpensive",
        note: "Feminine: rkheesa (رخيصة).",
        tip: "Rkhees is the opposite of ghaali. Use rkheesa when the item has a feminine noun.",
      },
      {
        ar: "بدي هادا",
        latin: "biddi haada",
        en: "I want this one",
        tip: "Biddi stays the same regardless of your gender. Change haada to haadi when choosing an item with a feminine noun.",
      },
    ],
  },
  {
    id: 11,
    title: "Make a little time",
    subtitle: "Today, tomorrow & a moment to pause",
    icon: "chat",
    tip: "Time words help turn a thought into a plan.",
    phrases: [
      {
        ar: "اليوم",
        latin: "il-yoom",
        en: "Today",
        tip: "Use il-yoom to place something today. The oo is long, like the vowel in “moon.”",
      },
      {
        ar: "بكرا",
        latin: "bukra",
        en: "Tomorrow",
        tip: "You’ve already met this in “bshoofak bukra” — see you tomorrow. Try saying the full phrase again.",
      },
      {
        ar: "مبارح",
        latin: "mbaareh",
        en: "Yesterday",
        tip: "Keep these three together: mbaareh, il-yoom, bukra — yesterday, today, tomorrow.",
      },
      {
        ar: "هلأ",
        latin: "halla’",
        en: "Now",
        note: "Another Palestinian form is هسّا (hassa).",
        tip: "The mark at the end of halla’ is a small stop in the voice. You’ll also hear hassa for “now.”",
      },
      {
        ar: "بعدين",
        latin: "ba‘dein",
        en: "Later",
        tip: "Ba‘dein can mean “later” or “afterward.” Its meaning depends on whether you’re postponing something or telling a sequence.",
      },
    ],
  },
  {
    id: 12,
    title: "How are you feeling?",
    subtitle: "Put a few feelings into words",
    icon: "smile",
    tip: "Adjectives often change with the person they describe.",
    phrases: [
      {
        ar: "مبسوط",
        latin: "mabsoot",
        en: "Happy",
        note: "Feminine: mabsoota (مبسوطة).",
        tip: "Say “ana mabsoot” if you’re a man or “ana mabsoota” if you’re a woman: I’m happy.",
      },
      {
        ar: "تعبان",
        latin: "ta‘baan",
        en: "Tired",
        note: "Feminine: ta‘baaneh (تعبانة).",
        tip: "Answer keefak with “ta‘baan” if you’re a man. A woman describing herself uses ta‘baaneh.",
      },
      {
        ar: "جوعان",
        latin: "joo‘aan",
        en: "Hungry",
        note: "Feminine: joo‘aaneh (جوعانة).",
        tip: "Combine a feeling and a request: “ana joo‘aan, biddi khubiz” — I’m hungry, I want bread. Use joo‘aaneh for a female speaker.",
      },
      {
        ar: "عطشان",
        latin: "‘atshaan",
        en: "Thirsty",
        note: "Feminine: ‘atshaaneh (عطشانة).",
        tip: "Follow ‘atshaan with “biddi mayy”: I want water. A female speaker describes herself as ‘atshaaneh.",
      },
      {
        ar: "مشغول",
        latin: "mashghool",
        en: "Busy",
        note: "Feminine: mashghooleh (مشغولة).",
        tip: "“Ana mashghool il-yoom” means “I’m busy today” for a male speaker. A female speaker uses mashghooleh.",
      },
    ],
  },
  {
    id: 13,
    title: "Let’s make a plan",
    subtitle: "Invitations, places & good company",
    icon: "map",
    tip: "Short invitations are a lovely way to use your Arabic.",
    phrases: [
      {
        ar: "شو رأيك؟",
        latin: "shu ra’yak? / shu ra’yik?",
        en: "What do you think?",
        note: "Ra’yak to a man; ra’yik to a woman.",
        tip: "Literally, this asks “what’s your opinion?” Use it to invite someone’s thoughts about an idea.",
      },
      {
        ar: "نروح؟",
        latin: "nrooh?",
        en: "Shall we go?",
        tip: "A rising voice turns nrooh into a question. Compare it with the invitation you know: “yalla nrooh!”",
      },
      {
        ar: "عالبيت",
        latin: "‘al-beit",
        en: "To the house",
        tip: "This combines “to” and “the house.” “Nrooh ‘al-beit?” means “shall we go home / to the house?”",
      },
      {
        ar: "عالسوق",
        latin: "‘as-soo’",
        en: "To the market",
        tip: "The s of soo’ blends with the article. Combine it with nrooh to suggest going to the market.",
      },
      {
        ar: "مع بعض",
        latin: "ma‘ ba‘d",
        en: "Together",
        tip: "“Nrooh ma‘ ba‘d?” means “shall we go together?” Both little marks represent the Arabic letter ع.",
      },
    ],
  },
  {
    id: 14,
    title: "Keep the conversation going",
    subtitle: "Ask, repeat & understand a little more",
    icon: "chat",
    tip: "Asking for help is part of speaking a new language.",
    phrases: [
      {
        ar: "مش فاهم",
        latin: "mish faahem",
        en: "I don’t understand",
        note: "A female speaker says mish faahmeh (مش فاهمة).",
        tip: "Mish makes this negative. Add “shway shway” to ask the other person to take it slowly.",
      },
      {
        ar: "كمان مرة",
        latin: "kamaan marra",
        en: "One more time",
        tip: "Ask someone to repeat with “kamaan marra, law samaht.” Marra is “a time” or “an occasion.”",
      },
      {
        ar: "شوي شوي",
        latin: "shway shway",
        en: "Little by little / slowly",
        tip: "Repeating shway softens the request: take it slowly. It’s also Zaytoun’s reminder that learning happens little by little.",
      },
      {
        ar: "شو يعني؟",
        latin: "shu ya‘ni?",
        en: "What does it mean?",
        tip: "Use shu ya‘ni when you hear an unfamiliar word. You can repeat the word after your question to make it clear.",
      },
      {
        ar: "بحكي عربي شوي",
        latin: "bahki ‘arabi shway",
        en: "I speak a little Arabic",
        tip: "Bahki means “I speak.” This sentence works for men and women and lets someone know you’re learning.",
      },
    ],
  },
  {
    id: 15,
    title: "A warm welcome",
    subtitle: "Everyday hospitality, from hello to goodbye",
    icon: "coffee",
    tip: "Bring a little warmth to your next visit.",
    phrases: [
      {
        ar: "تفضل",
        latin: "tfaddal",
        en: "Please, go ahead",
        note: "To a woman: tfaddali (تفضلي).",
        tip: "Tfaddal can invite a man to enter, sit, or take something you’re offering. Say tfaddali to a woman.",
      },
      {
        ar: "نورت",
        latin: "nawwart",
        en: "You’ve brightened the place",
        note: "To a woman: nawwarti (نورتي).",
        tip: "A warm welcome for a visitor: you’ve lit up the place. Use nawwart to a man and nawwarti to a woman.",
      },
      {
        ar: "يسلموا",
        latin: "yislamu",
        en: "Thanks a lot",
        tip: "Yislamu is a warm, informal thank-you, often heard after someone has done something kind for you.",
      },
      {
        ar: "الله يعطيك العافية",
        latin: "alla ya‘teek il-‘aafyeh",
        note: "To a woman: alla ya‘teeki il-‘aafyeh.",
        en: "May God give you well-being",
        tip: "Say this to appreciate someone’s effort or work. It’s a wish for their health and strength.",
      },
      {
        ar: "الله معك",
        latin: "alla ma‘ak / alla ma‘ik",
        en: "God be with you",
        note: "Ma‘ak to a man; ma‘ik to a woman.",
        tip: "This is a warm farewell. You may hear it in reply to ma‘ is-salaameh when someone is leaving.",
      },
    ],
  },
];
export const laterUnits = [
  {
    id: 2,
    title: "Out & about",
    subtitle: "A coffee. A conversation. A connection.",
    icon: "coffee",
    start: 4,
    end: 8,
  },
  {
    id: 3,
    title: "A little more everyday",
    subtitle: "Your people, your plans, your everyday world.",
    icon: "heart",
    start: 8,
    end: 12,
  },
  {
    id: 4,
    title: "Closer with every word",
    subtitle: "Express yourself. Make plans. Feel at home.",
    icon: "chat",
    start: 12,
    end: 16,
  },
];
